### ISSUE TITLE
Add Readme File for the Repository

### ISSUE THREAD

**Issue by Yeffian** [billyeatcookies/Kookie#1]
Add a readme file for the repository, it can be beneficial to the project in many ways.  It can tell other people why your project is useful, what they can do with your project, and how they can use it.

**Comment by salty-sweet** [comment]
why have you forsaken him yeff

**Comment by YeffyCodeGit** [comment]
it must be done

**Comment by salty-sweet** [comment]
he just started today give him a break

**Comment by YeffyCodeGit** [comment]
no
dont make me pull request kid

**Comment by ANF-Studios** [comment]
> he just started today give him a break

@salty-sweet // Me who commits around 25 times on average per day 😩.

**Comment by salty-sweet** [comment]
> > he just started today give him a break
> 
> @salty-sweet // Me who commits around 25 times on average per day 😩.

smh give us a break

**Comment by ANF-Studios** [comment]
Oh and, I forgot to point out. Issues are a good way to keep track of tasks.

**Comment by billyeatcookies** [comment]
a pull request have been opened regarding this issue ( see #2 )

**Comment by billyeatcookies** [comment]
# TODO

- [x] Official logo, short description, quick links
- [x] Language Feature Suggestions
- [ ] Contributing
- [ ] Key Features of Kookie
- [ ] Installation of Kookie
- [ ] Testing and running the examples
- [ ] Sample hello world program, to give a quick syntax-looks-alike to the viewers
- [ ] Example program screenshots
- [ ] Community
- [ ] Documentation
- [ ] Troubleshooting
- [ ] Docker
